FROM nvcr.io/nvidia/tensorflow:19.02-py2

LABEL maintainer "Jiaming Liu"
MAINTAINER Jiaming Liu <liujiaming@sensetime.com>
ENV IMAGE_BUILD_DATE 2019-07-02


# Install sudo
RUN apt-get update && \
    apt-get install -y sudo apt-utils curl

# Environment config
ENV DEBIAN_FRONTEND=noninteractive

# Add new sudo user
ARG user=sensetime
ARG passwd=sensetime
ARG uid=1000
ARG gid=1000
ENV USER=$user
ENV PASSWD=$passwd
ENV UID=$uid
ENV GID=$gid
RUN useradd --create-home -d /sensetime -m $USER && \
        echo "$USER:$PASSWD" | chpasswd && \
        usermod --shell /bin/bash $USER && \
        usermod -aG sudo $USER && \
        echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USER && \
        chmod 0440 /etc/sudoers.d/$USER && \
        usermod  --uid $UID $USER && \
        groupmod --gid $GID $USER

RUN sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sh -c '. /etc/lsb-release && echo "deb http://mirrors.ustc.edu.cn/ros/ubuntu/ $DISTRIB_CODENAME main" > /etc/apt/sources.list.d/ros-latest.list' && \
    apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654 && \
    apt-get clean && \
    apt-get update --fix-missing && \
    apt-get install -yq --no-install-recommends \
        ros-kinetic-desktop ros-kinetic-moveit ros-kinetic-ros-control ros-kinetic-ros-controllers iputils-ping ros-kinetic-trac-ik-kinematics-plugin ros-kinetic-catkin python-catkin-tools \
        pkg-config \
        libxau-dev \
        libxdmcp-dev \
        libxcb1-dev \
        libxext-dev \
        libx11-dev \
        libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
        libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 \
        libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
        libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 \
        libnss3 \
        libglu1
    # dpkg --remove --force-depends python-pyassimp && \

RUN echo "source /opt/ros/kinetic/setup.bash" >> /root/.bashrc && \
    pip install -U pip numpy && \
    pip install ruamel.yaml && \
    pip install https://download.pytorch.org/whl/cu100/torch-1.1.0-cp27-cp27mu-linux_x86_64.whl && \
    pip install torchvision && \ 
    pip install --upgrade cryptography && \
    python -m easy_install --upgrade pyOpenSSL && \
    # DEBIAN_FRONTEND=noninteractive apt-get install python-pyassimp && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN rosdep init && \
    rosdep update

# replace with other Ubuntu version if desired
# see: https://hub.docker.com/r/nvidia/opengl/
COPY --from=nvidia/cudagl:10.0-runtime-ubuntu16.04 \
  /usr/local/lib/x86_64-linux-gnu \
  /usr/local/lib/x86_64-linux-gnu

# replace with other Ubuntu version if desired
# see: https://hub.docker.com/r/nvidia/opengl/
COPY --from=nvidia/cudagl:10.0-runtime-ubuntu16.04 \
  /usr/local/share/glvnd/egl_vendor.d/10_nvidia.json \
  /usr/local/share/glvnd/egl_vendor.d/10_nvidia.json

RUN echo '/usr/local/lib/x86_64-linux-gnu' >> /etc/ld.so.conf.d/glvnd.conf && \
    ldconfig && \
    echo '/usr/local/$LIB/libGL.so.1' >> /etc/ld.so.preload && \
    echo '/usr/local/$LIB/libEGL.so.1' >> /etc/ld.so.preload

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

USER $USER
WORKDIR /sensetime

# USER original_user
# RUN groupadd -r sensetime && useradd -r -g sensetime sensetime
# USER sensetime
