// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vel.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "vel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gos_test {

namespace {

const ::google::protobuf::Descriptor* vel_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  vel_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_vel_2eproto() {
  protobuf_AddDesc_vel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "vel.proto");
  GOOGLE_CHECK(file != NULL);
  vel_descriptor_ = file->message_type(0);
  static const int vel_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, linear_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, angular_z_),
  };
  vel_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      vel_descriptor_,
      vel::default_instance_,
      vel_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(vel));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_vel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    vel_descriptor_, &vel::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_vel_2eproto() {
  delete vel::default_instance_;
  delete vel_reflection_;
}

void protobuf_AddDesc_vel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tvel.proto\022\010gos_test\"*\n\003vel\022\020\n\010linear_x"
    "\030\001 \002(\001\022\021\n\tangular_z\030\002 \002(\001", 65);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "vel.proto", &protobuf_RegisterTypes);
  vel::default_instance_ = new vel();
  vel::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_vel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_vel_2eproto {
  StaticDescriptorInitializer_vel_2eproto() {
    protobuf_AddDesc_vel_2eproto();
  }
} static_descriptor_initializer_vel_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int vel::kLinearXFieldNumber;
const int vel::kAngularZFieldNumber;
#endif  // !_MSC_VER

vel::vel()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gos_test.vel)
}

void vel::InitAsDefaultInstance() {
}

vel::vel(const vel& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gos_test.vel)
}

void vel::SharedCtor() {
  _cached_size_ = 0;
  linear_x_ = 0;
  angular_z_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

vel::~vel() {
  // @@protoc_insertion_point(destructor:gos_test.vel)
  SharedDtor();
}

void vel::SharedDtor() {
  if (this != default_instance_) {
  }
}

void vel::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* vel::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return vel_descriptor_;
}

const vel& vel::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_vel_2eproto();
  return *default_instance_;
}

vel* vel::default_instance_ = NULL;

vel* vel::New() const {
  return new vel;
}

void vel::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<vel*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(linear_x_, angular_z_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool vel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gos_test.vel)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required double linear_x = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &linear_x_)));
          set_has_linear_x();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_angular_z;
        break;
      }

      // required double angular_z = 2;
      case 2: {
        if (tag == 17) {
         parse_angular_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &angular_z_)));
          set_has_angular_z();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gos_test.vel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gos_test.vel)
  return false;
#undef DO_
}

void vel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gos_test.vel)
  // required double linear_x = 1;
  if (has_linear_x()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->linear_x(), output);
  }

  // required double angular_z = 2;
  if (has_angular_z()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->angular_z(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:gos_test.vel)
}

::google::protobuf::uint8* vel::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gos_test.vel)
  // required double linear_x = 1;
  if (has_linear_x()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->linear_x(), target);
  }

  // required double angular_z = 2;
  if (has_angular_z()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->angular_z(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:gos_test.vel)
  return target;
}

int vel::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required double linear_x = 1;
    if (has_linear_x()) {
      total_size += 1 + 8;
    }

    // required double angular_z = 2;
    if (has_angular_z()) {
      total_size += 1 + 8;
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void vel::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const vel* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const vel*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void vel::MergeFrom(const vel& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_linear_x()) {
      set_linear_x(from.linear_x());
    }
    if (from.has_angular_z()) {
      set_angular_z(from.angular_z());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void vel::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void vel::CopyFrom(const vel& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool vel::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void vel::Swap(vel* other) {
  if (other != this) {
    std::swap(linear_x_, other->linear_x_);
    std::swap(angular_z_, other->angular_z_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata vel::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = vel_descriptor_;
  metadata.reflection = vel_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gos_test

// @@protoc_insertion_point(global_scope)
