// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vel.proto

#ifndef PROTOBUF_vel_2eproto__INCLUDED
#define PROTOBUF_vel_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace gos_test {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_vel_2eproto();
void protobuf_AssignDesc_vel_2eproto();
void protobuf_ShutdownFile_vel_2eproto();

class vel;

// ===================================================================

class vel : public ::google::protobuf::Message {
 public:
  vel();
  virtual ~vel();

  vel(const vel& from);

  inline vel& operator=(const vel& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const vel& default_instance();

  void Swap(vel* other);

  // implements Message ----------------------------------------------

  vel* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const vel& from);
  void MergeFrom(const vel& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required double linear_x = 1;
  inline bool has_linear_x() const;
  inline void clear_linear_x();
  static const int kLinearXFieldNumber = 1;
  inline double linear_x() const;
  inline void set_linear_x(double value);

  // required double angular_z = 2;
  inline bool has_angular_z() const;
  inline void clear_angular_z();
  static const int kAngularZFieldNumber = 2;
  inline double angular_z() const;
  inline void set_angular_z(double value);

  // @@protoc_insertion_point(class_scope:gos_test.vel)
 private:
  inline void set_has_linear_x();
  inline void clear_has_linear_x();
  inline void set_has_angular_z();
  inline void clear_has_angular_z();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double linear_x_;
  double angular_z_;
  friend void  protobuf_AddDesc_vel_2eproto();
  friend void protobuf_AssignDesc_vel_2eproto();
  friend void protobuf_ShutdownFile_vel_2eproto();

  void InitAsDefaultInstance();
  static vel* default_instance_;
};
// ===================================================================


// ===================================================================

// vel

// required double linear_x = 1;
inline bool vel::has_linear_x() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void vel::set_has_linear_x() {
  _has_bits_[0] |= 0x00000001u;
}
inline void vel::clear_has_linear_x() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void vel::clear_linear_x() {
  linear_x_ = 0;
  clear_has_linear_x();
}
inline double vel::linear_x() const {
  // @@protoc_insertion_point(field_get:gos_test.vel.linear_x)
  return linear_x_;
}
inline void vel::set_linear_x(double value) {
  set_has_linear_x();
  linear_x_ = value;
  // @@protoc_insertion_point(field_set:gos_test.vel.linear_x)
}

// required double angular_z = 2;
inline bool vel::has_angular_z() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void vel::set_has_angular_z() {
  _has_bits_[0] |= 0x00000002u;
}
inline void vel::clear_has_angular_z() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void vel::clear_angular_z() {
  angular_z_ = 0;
  clear_has_angular_z();
}
inline double vel::angular_z() const {
  // @@protoc_insertion_point(field_get:gos_test.vel.angular_z)
  return angular_z_;
}
inline void vel::set_angular_z(double value) {
  set_has_angular_z();
  angular_z_ = value;
  // @@protoc_insertion_point(field_set:gos_test.vel.angular_z)
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace gos_test

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vel_2eproto__INCLUDED
