// Generated by gencpp from file am_msgs/Object.msg
// DO NOT EDIT!


#ifndef AM_MSGS_MESSAGE_OBJECT_H
#define AM_MSGS_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <am_msgs/Rect.h>
#include <geometry_msgs/Point.h>

namespace am_msgs
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : object_index(0)
    , confidence(0.0)
    , bounding_box_cv()
    , location_bv()
    , label(0)  {
    }
  Object_(const ContainerAllocator& _alloc)
    : object_index(0)
    , confidence(0.0)
    , bounding_box_cv(_alloc)
    , location_bv(_alloc)
    , label(0)  {
  (void)_alloc;
    }



   typedef int32_t _object_index_type;
  _object_index_type object_index;

   typedef float _confidence_type;
  _confidence_type confidence;

   typedef  ::am_msgs::Rect_<ContainerAllocator>  _bounding_box_cv_type;
  _bounding_box_cv_type bounding_box_cv;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _location_bv_type;
  _location_bv_type location_bv;

   typedef uint8_t _label_type;
  _label_type label;



  enum {
    LABEL_UNKNOWN = 0u,
    LABEL_PEDESTRIAN = 1u,
    LABEL_CONE = 2u,
    LABEL_GOLF = 3u,
    LABEL_SPRINKLER = 4u,
  };


  typedef boost::shared_ptr< ::am_msgs::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_msgs::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::am_msgs::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::am_msgs::Object > ObjectPtr;
typedef boost::shared_ptr< ::am_msgs::Object const> ObjectConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_msgs::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_msgs::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'am_msgs': ['/home/linsc/ROS_Project/Sensetime_ws/dengwenjun_old_ws/src/am_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_msgs::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_msgs::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_msgs::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_msgs::Object_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0c9b334f865e3aab40d33e895236278a";
  }

  static const char* value(const ::am_msgs::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0c9b334f865e3aabULL;
  static const uint64_t static_value2 = 0x40d33e895236278aULL;
};

template<class ContainerAllocator>
struct DataType< ::am_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_msgs/Object";
  }

  static const char* value(const ::am_msgs::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_msgs::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 object_index\n\
float32 confidence # A value between 0.0 and 1.0.\n\
Rect bounding_box_cv # A bounding box on the camera coordinate.\n\
geometry_msgs/Point[] location_bv # A location on the bird-view coordinate. Z component is always 0.\n\
uint8 label\n\
uint8 LABEL_UNKNOWN=0\n\
uint8 LABEL_PEDESTRIAN=1\n\
uint8 LABEL_CONE=2\n\
uint8 LABEL_GOLF=3\n\
uint8 LABEL_SPRINKLER=4\n\
\n\
================================================================================\n\
MSG: am_msgs/Rect\n\
float32 x\n\
float32 y\n\
float32 width\n\
float32 height\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::am_msgs::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_msgs::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.object_index);
      stream.next(m.confidence);
      stream.next(m.bounding_box_cv);
      stream.next(m.location_bv);
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_msgs::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_msgs::Object_<ContainerAllocator>& v)
  {
    s << indent << "object_index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.object_index);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
    s << indent << "bounding_box_cv: ";
    s << std::endl;
    Printer< ::am_msgs::Rect_<ContainerAllocator> >::stream(s, indent + "  ", v.bounding_box_cv);
    s << indent << "location_bv[]" << std::endl;
    for (size_t i = 0; i < v.location_bv.size(); ++i)
    {
      s << indent << "  location_bv[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.location_bv[i]);
    }
    s << indent << "label: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_MSGS_MESSAGE_OBJECT_H
