// Generated by gencpp from file am_msgs/StateInput.msg
// DO NOT EDIT!


#ifndef AM_MSGS_MESSAGE_STATEINPUT_H
#define AM_MSGS_MESSAGE_STATEINPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace am_msgs
{
template <class ContainerAllocator>
struct StateInput_
{
  typedef StateInput_<ContainerAllocator> Type;

  StateInput_()
    : header()
    , pathSegmentationBlocked(false)
    , pathDetectionBlocked(false)
    , turningDirectionLeft(false)  {
    }
  StateInput_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , pathSegmentationBlocked(false)
    , pathDetectionBlocked(false)
    , turningDirectionLeft(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _pathSegmentationBlocked_type;
  _pathSegmentationBlocked_type pathSegmentationBlocked;

   typedef uint8_t _pathDetectionBlocked_type;
  _pathDetectionBlocked_type pathDetectionBlocked;

   typedef uint8_t _turningDirectionLeft_type;
  _turningDirectionLeft_type turningDirectionLeft;





  typedef boost::shared_ptr< ::am_msgs::StateInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am_msgs::StateInput_<ContainerAllocator> const> ConstPtr;

}; // struct StateInput_

typedef ::am_msgs::StateInput_<std::allocator<void> > StateInput;

typedef boost::shared_ptr< ::am_msgs::StateInput > StateInputPtr;
typedef boost::shared_ptr< ::am_msgs::StateInput const> StateInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am_msgs::StateInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am_msgs::StateInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace am_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'am_msgs': ['/home/linsc/ROS_Project/Sensetime_ws/dengwenjun_old_ws/src/am_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::am_msgs::StateInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am_msgs::StateInput_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_msgs::StateInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am_msgs::StateInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_msgs::StateInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am_msgs::StateInput_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am_msgs::StateInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66f3e8700901a4c81c50fee4c374e6c7";
  }

  static const char* value(const ::am_msgs::StateInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66f3e8700901a4c8ULL;
  static const uint64_t static_value2 = 0x1c50fee4c374e6c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::am_msgs::StateInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am_msgs/StateInput";
  }

  static const char* value(const ::am_msgs::StateInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am_msgs::StateInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
bool pathSegmentationBlocked\n\
bool pathDetectionBlocked\n\
bool turningDirectionLeft\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::am_msgs::StateInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am_msgs::StateInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.pathSegmentationBlocked);
      stream.next(m.pathDetectionBlocked);
      stream.next(m.turningDirectionLeft);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StateInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am_msgs::StateInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am_msgs::StateInput_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "pathSegmentationBlocked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pathSegmentationBlocked);
    s << indent << "pathDetectionBlocked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pathDetectionBlocked);
    s << indent << "turningDirectionLeft: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.turningDirectionLeft);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM_MSGS_MESSAGE_STATEINPUT_H
