// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vel.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "vel.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace gos_test {

namespace {

const ::google::protobuf::Descriptor* vel_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  vel_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_vel_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_vel_2eproto() {
  protobuf_AddDesc_vel_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "vel.proto");
  GOOGLE_CHECK(file != NULL);
  vel_descriptor_ = file->message_type(0);
  static const int vel_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, linear_x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, angular_z_),
  };
  vel_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      vel_descriptor_,
      vel::default_instance_,
      vel_offsets_,
      -1,
      -1,
      -1,
      sizeof(vel),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(vel, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_vel_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      vel_descriptor_, &vel::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_vel_2eproto() {
  delete vel::default_instance_;
  delete vel_reflection_;
}

void protobuf_AddDesc_vel_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_vel_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tvel.proto\022\010gos_test\"*\n\003vel\022\020\n\010linear_x"
    "\030\001 \001(\001\022\021\n\tangular_z\030\002 \001(\001b\006proto3", 73);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "vel.proto", &protobuf_RegisterTypes);
  vel::default_instance_ = new vel();
  vel::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_vel_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_vel_2eproto {
  StaticDescriptorInitializer_vel_2eproto() {
    protobuf_AddDesc_vel_2eproto();
  }
} static_descriptor_initializer_vel_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int vel::kLinearXFieldNumber;
const int vel::kAngularZFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

vel::vel()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:gos_test.vel)
}

void vel::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

vel::vel(const vel& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:gos_test.vel)
}

void vel::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  linear_x_ = 0;
  angular_z_ = 0;
}

vel::~vel() {
  // @@protoc_insertion_point(destructor:gos_test.vel)
  SharedDtor();
}

void vel::SharedDtor() {
  if (this != default_instance_) {
  }
}

void vel::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* vel::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return vel_descriptor_;
}

const vel& vel::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_vel_2eproto();
  return *default_instance_;
}

vel* vel::default_instance_ = NULL;

vel* vel::New(::google::protobuf::Arena* arena) const {
  vel* n = new vel;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void vel::Clear() {
// @@protoc_insertion_point(message_clear_start:gos_test.vel)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(vel, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<vel*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(linear_x_, angular_z_);

#undef ZR_HELPER_
#undef ZR_

}

bool vel::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:gos_test.vel)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional double linear_x = 1;
      case 1: {
        if (tag == 9) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &linear_x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(17)) goto parse_angular_z;
        break;
      }

      // optional double angular_z = 2;
      case 2: {
        if (tag == 17) {
         parse_angular_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &angular_z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:gos_test.vel)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:gos_test.vel)
  return false;
#undef DO_
}

void vel::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:gos_test.vel)
  // optional double linear_x = 1;
  if (this->linear_x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->linear_x(), output);
  }

  // optional double angular_z = 2;
  if (this->angular_z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(2, this->angular_z(), output);
  }

  // @@protoc_insertion_point(serialize_end:gos_test.vel)
}

::google::protobuf::uint8* vel::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:gos_test.vel)
  // optional double linear_x = 1;
  if (this->linear_x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->linear_x(), target);
  }

  // optional double angular_z = 2;
  if (this->angular_z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(2, this->angular_z(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:gos_test.vel)
  return target;
}

int vel::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:gos_test.vel)
  int total_size = 0;

  // optional double linear_x = 1;
  if (this->linear_x() != 0) {
    total_size += 1 + 8;
  }

  // optional double angular_z = 2;
  if (this->angular_z() != 0) {
    total_size += 1 + 8;
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void vel::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:gos_test.vel)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const vel* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const vel>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:gos_test.vel)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:gos_test.vel)
    MergeFrom(*source);
  }
}

void vel::MergeFrom(const vel& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:gos_test.vel)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.linear_x() != 0) {
    set_linear_x(from.linear_x());
  }
  if (from.angular_z() != 0) {
    set_angular_z(from.angular_z());
  }
}

void vel::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:gos_test.vel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void vel::CopyFrom(const vel& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:gos_test.vel)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool vel::IsInitialized() const {

  return true;
}

void vel::Swap(vel* other) {
  if (other == this) return;
  InternalSwap(other);
}
void vel::InternalSwap(vel* other) {
  std::swap(linear_x_, other->linear_x_);
  std::swap(angular_z_, other->angular_z_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata vel::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = vel_descriptor_;
  metadata.reflection = vel_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// vel

// optional double linear_x = 1;
void vel::clear_linear_x() {
  linear_x_ = 0;
}
 double vel::linear_x() const {
  // @@protoc_insertion_point(field_get:gos_test.vel.linear_x)
  return linear_x_;
}
 void vel::set_linear_x(double value) {
  
  linear_x_ = value;
  // @@protoc_insertion_point(field_set:gos_test.vel.linear_x)
}

// optional double angular_z = 2;
void vel::clear_angular_z() {
  angular_z_ = 0;
}
 double vel::angular_z() const {
  // @@protoc_insertion_point(field_get:gos_test.vel.angular_z)
  return angular_z_;
}
 void vel::set_angular_z(double value) {
  
  angular_z_ = value;
  // @@protoc_insertion_point(field_set:gos_test.vel.angular_z)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace gos_test

// @@protoc_insertion_point(global_scope)
