# Teleop configuration for PS4 joystick using the x-pad configuration.
teleop_twist_joy:
  axis_linear: 1
  scale_linear: 0.4
  scale_linear_turbo: 1.0
  axis_angular: 2  # or 2 is better
  scale_angular: 1.3
  enable_button: 6
  enable_turbo_button: 7
joy_node:
  deadzone: 0.1
  autorepeat_rate: 20
#  dev: /dev/input/js1
