// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vel.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vel_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_vel_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_vel_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vel_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_vel_2eproto;
namespace gos_test {
class vel;
class velDefaultTypeInternal;
extern velDefaultTypeInternal _vel_default_instance_;
}  // namespace gos_test
PROTOBUF_NAMESPACE_OPEN
template<> ::gos_test::vel* Arena::CreateMaybeMessage<::gos_test::vel>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace gos_test {

// ===================================================================

class vel :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:gos_test.vel) */ {
 public:
  vel();
  virtual ~vel();

  vel(const vel& from);
  vel(vel&& from) noexcept
    : vel() {
    *this = ::std::move(from);
  }

  inline vel& operator=(const vel& from) {
    CopyFrom(from);
    return *this;
  }
  inline vel& operator=(vel&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const vel& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const vel* internal_default_instance() {
    return reinterpret_cast<const vel*>(
               &_vel_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(vel& a, vel& b) {
    a.Swap(&b);
  }
  inline void Swap(vel* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline vel* New() const final {
    return CreateMaybeMessage<vel>(nullptr);
  }

  vel* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<vel>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const vel& from);
  void MergeFrom(const vel& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(vel* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "gos_test.vel";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_vel_2eproto);
    return ::descriptor_table_vel_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLinearXFieldNumber = 1,
    kAngularZFieldNumber = 2,
  };
  // required double linear_x = 1;
  bool has_linear_x() const;
  private:
  bool _internal_has_linear_x() const;
  public:
  void clear_linear_x();
  double linear_x() const;
  void set_linear_x(double value);
  private:
  double _internal_linear_x() const;
  void _internal_set_linear_x(double value);
  public:

  // required double angular_z = 2;
  bool has_angular_z() const;
  private:
  bool _internal_has_angular_z() const;
  public:
  void clear_angular_z();
  double angular_z() const;
  void set_angular_z(double value);
  private:
  double _internal_angular_z() const;
  void _internal_set_angular_z(double value);
  public:

  // @@protoc_insertion_point(class_scope:gos_test.vel)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double linear_x_;
  double angular_z_;
  friend struct ::TableStruct_vel_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// vel

// required double linear_x = 1;
inline bool vel::_internal_has_linear_x() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool vel::has_linear_x() const {
  return _internal_has_linear_x();
}
inline void vel::clear_linear_x() {
  linear_x_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double vel::_internal_linear_x() const {
  return linear_x_;
}
inline double vel::linear_x() const {
  // @@protoc_insertion_point(field_get:gos_test.vel.linear_x)
  return _internal_linear_x();
}
inline void vel::_internal_set_linear_x(double value) {
  _has_bits_[0] |= 0x00000001u;
  linear_x_ = value;
}
inline void vel::set_linear_x(double value) {
  _internal_set_linear_x(value);
  // @@protoc_insertion_point(field_set:gos_test.vel.linear_x)
}

// required double angular_z = 2;
inline bool vel::_internal_has_angular_z() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool vel::has_angular_z() const {
  return _internal_has_angular_z();
}
inline void vel::clear_angular_z() {
  angular_z_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double vel::_internal_angular_z() const {
  return angular_z_;
}
inline double vel::angular_z() const {
  // @@protoc_insertion_point(field_get:gos_test.vel.angular_z)
  return _internal_angular_z();
}
inline void vel::_internal_set_angular_z(double value) {
  _has_bits_[0] |= 0x00000002u;
  angular_z_ = value;
}
inline void vel::set_angular_z(double value) {
  _internal_set_angular_z(value);
  // @@protoc_insertion_point(field_set:gos_test.vel.angular_z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace gos_test

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_vel_2eproto
