FROM registry.sensetime.com/gophield/gophield:ubuntu18.04 as ci-build
LABEL repository=gophield-ci

COPY . /root/gophield

ENV ROS_LANG_DISABLE=genlisp:gennodejs:geneus
ENV ROS_MASTER_URI=http://localhost:11311/
RUN pip install -U rosdep rosinstall_generator wstool rosinstall six vcstools
RUN /bin/bash -c '. /opt/ros/melodic/setup.bash; cd /root/gophield/ros_ws; catkin_make'
RUN /bin/bash -c '. /root/gophield/ros_ws/devel/setup.bash'