(cl:in-package am_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          PATHSEGMENTATIONBLOCKED-VAL
          PATHSEGMENTATIONBLOCKED
          PATHDETECTIONBLOCKED-VAL
          PATHDETECTIONBLOCKED
          TURNINGDIRECTIONLEFT-VAL
          TURNINGDIRECTIONLEFT
))